//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionReservas
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserva
    {
        public int codigo { get; set; }
        public Nullable<int> cancha { get; set; }
        public Nullable<int> cliente { get; set; }
        public Nullable<int> profesor { get; set; }
        public string fecha { get; set; }
        public string hora_ini { get; set; }
        public string hora_fin { get; set; }
    
        public virtual cancha cancha1 { get; set; }
        public virtual cliente cliente1 { get; set; }
        public virtual profesor profesor1 { get; set; }
    }
}
