//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionReservas
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int codigo { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> rol { get; set; }
    
        public virtual rol rol1 { get; set; }
    }
}
